### ISSUE TITLE
[BUG] Positional args never used

### ISSUE THREAD

**Issue by Starmania** [ax/apk.sh#17]
### Information
1. **apk.sh version** : v1.0.4
2. **Operating System (Mac, Linux, Windows)** : N/A
3. **APK From? (Playstore, ROM, Other)** : N/A

### apk.sh output
N/A

### Steps to Reproduce
1. Run any command accepting positional args (build, decode, patch)
2. Theses args are saved but never used

### Questions to ask before submission
- [x] Are you using the latest apk.sh version?

[This StackOverflow answer](https://stackoverflow.com/a/14203146)  seems to have been a source when this file was created. But some things are missing (the definition of the POSITIONAL_ARGS variable and the restoration of positional parameters)...

**Comment by ax** [comment]
It's a feature! :beetle:

**Comment by Starmania** [comment]
🧐🧐
