### ISSUE TITLE
download adb as a tool

### ISSUE THREAD

**Issue by jeromew** [ax/apk.sh#22]
Hello,

adb for linux can be downloaded in platform-tools via the url
https://dl.google.com/android/repository/platform-tools-latest-linux.zip

it could be interesting to add adb to the auto-download mechanism.

**Comment by ax** [comment]
Wanna code it? :)

**Comment by jeromew** [comment]
yes I'll do it. I'll push a PR later

**Comment by jeromew** [comment]
Install sdk platform-tools when adb is not found

cf https://github.com/ax/apk.sh/pull/26

I realised platform-tools can be installed via sdkmanager so
I extracted the cmdline tools installation in their own function shared by `install_buildtools` and `install_platformtools`

**Comment by ax** [comment]
It seems ok!
Thank you @jeromew!
PR merged. v1.0.8.
