### ISSUE TITLE
[BUG] Could not smali file: XYZ already interned

### ISSUE THREAD

**Issue by AltayAkkus** [ax/apk.sh#30]
### Information
1. **apk.sh version** : 1.0.8
2. **Operating System (Mac, Linux, Windows)** : Linux, Windows etc.
3. **APK From? (Playstore, ROM, Other)** : PlayStore

### apk.sh output
```
I: Smaling smali_assets folder into assets.dex
xyz/smali_assets/audience_network/javax/annotation/concurrent/ThreadSafe.smali
[>] Sorry!
[!] java -jar /home/me/.apk.sh/apktool_2.9.3.jar b -d myapk -o myapk.gagdet.apk --use-aapt2 return errors!
[>] Bye!
```

### Steps to Reproduce
1. `apk.sh patch myfile.apk`

### APK
Is not needed.

### Questions to ask before submission
Are you using the latest apk.sh version? Yes

The thing is that `apktool` encounters problems with certain APKs, see https://github.com/iBotPeaches/Apktool/issues/2784 . 

This can be fixed by using the option `--only-main-classes` while decoding the `.apk`, but this feature is not supported by apk.sh.

**Comment by IrvanWijayaSardam** [comment]
is it already being merged to latest version ? i need --only-main-classes

**Comment by ax** [comment]
Done.
