### ISSUE TITLE
script.js into APK

### ISSUE THREAD

**Issue by mbakgun** [ax/apk.sh#37]
Request : Integrate script.js into APK without adb push

Details : Hi, thank you for the script, 
I am currently using the following commands to patch an APK and run a script:

```
adb push script.js /data/local/tmp

./apk.sh patch <apk_name> --arch arm --gadget-conf <config.json>

adb install file.gadget.apk
```

I would like to know if it is possible to integrate `script.js` directly into the APK without using `adb push`, and then execute it. According to [this link](https://github.com/frida/frida/issues/653), it seems feasible. Could you please provide(if possible) guidance on how to achieve this using apk.sh?

Thank you!

**Comment by ax** [comment]
Hi @mbakgun.
Yeah you can pass a `config.json` that fit your needs!
From Frida docs: A supported configuration keys is `path`: string specifying the filesystem path to the script to load. May also be a path relative to where the Gadget binary resides.
What about putting the script in $APK_DIR/lib/$ARCH_DIR/?

**Comment by mbakgun** [comment]
Thanks 👍
